kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.issuerName}}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        {{ if eq .Values.environment "prod" }}
        - {{ .Values.issuerName}}.{{ .Values.domainName}}
        {{ else }}
        - {{ .Values.issuerName}}-{{ .Values.environment}}.{{ .Values.domainName}}
        {{ end }}
      secretName: tls-secret-{{ .Values.issuerName}}
  rules:
    {{ if eq .Values.environment "prod" }}
    - host: {{ .Values.issuerName}}.{{ .Values.domainName}}
    {{ else }}
    - host: {{ .Values.issuerName}}-{{ .Values.environment}}.{{ .Values.domainName}}
    {{ end }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix 
            backend:
              service:
                name: {{ .Values.issuerName}}
                port:
                  number: 8080