kind: ConfigMap
apiVersion: v1
metadata:
  name: issuer-kit-admin-config
  namespace: issuer-kit
  selfLink: /api/v1/namespaces/issuer-kit/configmaps/issuer-kit-admin-config
  uid:  
  resourceVersion:  
  creationTimestamp:  
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: issuer-kit-admin
    meta.helm.sh/release-namespace: issuer-kit
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time:  
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:config.json: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
data:
  config.json: |-
    {
      "env": "prod",
      "issuer": {
        "name": "BuyBC Issuer Admin",
        "publicUrl": "https://buybc-issuer.apps.ds2isl2c.canadaeast.aroapp.io"
      },
      "authentication": {
        "enabled": true,
        "oidcSettings": {
          "authority": "https://sso.quartech.app/auth/realms/buybc",
          "clientId": "buybc-admin",
          "redirectUri": "https://buybc-issuer-admin.apps.ds2isl2c.canadaeast.aroapp.io/oidc-callback",
          "redirect_uri": "https://buybc-issuer-admin.apps.ds2isl2c.canadaeast.aroapp.io/oidc-callback-error",
          "responseType": "code",
          "scope": "openid profile email",
          "automaticSilentRenew": true,
          "silentRedirectUri": "https://buybc-issuer-admin.apps.ds2isl2c.canadaeast.aroapp.io/silent-renew-oidc.html",
          "post_logout_redirect_uri": "https://buybc-issuer-admin.apps.ds2isl2c.canadaeast.aroapp.io"
        }
      },
      "apiServer": {
        "url": "/api"
      }
    }
